# Generated by Django 5.1.1 on 2024-10-09 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
        ('patients', '0002_alter_patient_dob_alter_patient_first_name_and_more'),
        ('reception', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceptionPatient',
            fields=[
                ('patient_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='patients.patient')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
            ],
            bases=('patients.patient',),
        ),
        migrations.RenameModel(
            old_name='Patient',
            new_name='Reception',
        ),
    ]
