# Generated by Django 5.1.1 on 2024-10-09 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
        ('reception', '0003_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='reception',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reception', to='hospital.department'),
            preserve_default=False,
        ),
    ]
