# Generated by Django 5.1.1 on 2024-10-09 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_medicalrecord'),
        ('pharmacy', '0002_remove_prescription_date_prescribed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='medicine_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='pharmacist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.pharmacist'),
        ),
    ]
